name: memory_match_game
description: "A Flutter project for a memory match game."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.9.2

dependencies:
    pixelarticons: ^0.4.0
    http: ^1.2.0
    shared_preferences: ^2.2.2
    equatable: ^2.0.5
    path_provider: ^2.1.2
    image_picker: ^1.0.7
    just_audio: ^0.9.36
    socket_io_client: ^2.0.3+1
    video_player: ^2.8.2
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/videos/
        - assets/images/
        - assets/sounds/
        - assets/fonts/
        - assets/icons/
    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto.ttf
        - family: PressStart2P
          fonts:
              - asset: assets/fonts/PressStart2P.ttf
