const POKEMON_LIST = [
	{id: 1, name: "Abra"},
	{id: 2, name: "Aerodactyl"},
	{id: 3, name: "Alakazam"},
	{id: 4, name: "Arbok"},
	{id: 5, name: "Arcanine"},
	{id: 6, name: "Articuno"},
	{id: 7, name: "Beedrill"},
	{id: 8, name: "Bellsprout"},
	{id: 9, name: "Blastoise"},
	{id: 10, name: "Bulbasaur"},
	{id: 11, name: "Butterfree"},
	{id: 12, name: "Caterpie"},
	{id: 13, name: "Chansey"},
	{id: 14, name: "Charizard"},
	{id: 15, name: "Charmander"},
	{id: 16, name: "Charmeleon"},
	{id: 17, name: "Clefable"},
	{id: 18, name: "Clefairy"},
	{id: 19, name: "Cloyster"},
	{id: 20, name: "Cubone"},
	{id: 21, name: "Dewgong"},
	{id: 22, name: "Diglett"},
	{id: 23, name: "Ditto"},
	{id: 24, name: "Dodrio"},
	{id: 25, name: "Doduo"},
	{id: 26, name: "Dragonair"},
	{id: 27, name: "Dragonite"},
	{id: 28, name: "Dratini"},
	{id: 29, name: "Drowzee"},
	{id: 30, name: "Dugtrio"},
	{id: 31, name: "Eevee"},
	{id: 32, name: "Ekans"},
	{id: 33, name: "Electabuzz"},
	{id: 34, name: "Electrode"},
	{id: 35, name: "Exeggcute"},
	{id: 36, name: "Exeggutor"},
	{id: 37, name: "Farfetch'd"},
	{id: 38, name: "Fearow"},
	{id: 39, name: "Flareon"},
	{id: 40, name: "Gastly"},
	{id: 41, name: "Gengar"},
	{id: 42, name: "Geodude"},
	{id: 43, name: "Gloom"},
	{id: 44, name: "Golbat"},
	{id: 45, name: "Goldeen"},
	{id: 46, name: "Golduck"},
	{id: 47, name: "Golem"},
	{id: 48, name: "Graveler"},
	{id: 49, name: "Grimer"},
	{id: 50, name: "Growlithe"},
	{id: 51, name: "Gyarados"},
	{id: 52, name: "Haunter"},
	{id: 53, name: "Hitmonchan"},
	{id: 54, name: "Hitmonlee"},
	{id: 55, name: "Horsea"},
	{id: 56, name: "Hypno"},
	{id: 57, name: "Ivysaur"},
	{id: 58, name: "Jigglypuff"},
	{id: 59, name: "Jolteon"},
	{id: 60, name: "Jynx"},
	{id: 61, name: "Kabuto"},
	{id: 62, name: "Kabutops"},
	{id: 63, name: "Kadabra"},
	{id: 64, name: "Kakuna"},
	{id: 65, name: "Kangaskhan"},
	{id: 66, name: "Kingler"},
	{id: 67, name: "Koffing"},
	{id: 68, name: "Krabby"},
	{id: 69, name: "Lapras"},
	{id: 70, name: "Lickitung"},
	{id: 71, name: "Machamp"},
	{id: 72, name: "Machoke"},
	{id: 73, name: "Machop"},
	{id: 74, name: "Magikarp"},
	{id: 75, name: "Magmar"},
	{id: 76, name: "Magnemite"},
	{id: 77, name: "Magneton"},
	{id: 78, name: "Mankey"},
	{id: 79, name: "Marowak"},
	{id: 80, name: "Meowth"},
	{id: 81, name: "Metapod"},
	{id: 82, name: "Mew"},
	{id: 83, name: "Mewtwo"},
	{id: 84, name: "Moltres"},
	{id: 85, name: "Mr. Mime"},
	{id: 86, name: "Muk"},
	{id: 87, name: "Nidoking"},
	{id: 88, name: "Nidoqueen"},
	{id: 89, name: "Nidoran (female)"},
	{id: 90, name: "Nidoran (male)"},
	{id: 91, name: "Nidorina"},
	{id: 92, name: "Nidorino"},
	{id: 93, name: "Ninetales"},
	{id: 94, name: "Oddish"},
	{id: 95, name: "Omanyte"},
	{id: 96, name: "Omastar"},
	{id: 97, name: "Onix"},
	{id: 98, name: "Paras"},
	{id: 99, name: "Parasect"},
	{id: 100, name: "Persian"},
	{id: 101, name: "Pidgeot"},
	{id: 102, name: "Pidgeotto"},
	{id: 103, name: "Pidgey"},
	{id: 104, name: "Pikachu"},
	{id: 105, name: "Pinsir"},
	{id: 106, name: "Poliwag"},
	{id: 107, name: "Poliwhirl"},
	{id: 108, name: "Poliwrath"},
	{id: 109, name: "Ponyta"},
	{id: 110, name: "Porygon"},
	{id: 111, name: "Primeape"},
	{id: 112, name: "Psyduck"},
	{id: 113, name: "Raichu"},
	{id: 114, name: "Rapidash"},
	{id: 115, name: "Raticate"},
	{id: 116, name: "Rattata"},
	{id: 117, name: "Rhydon"},
	{id: 118, name: "Rhyhorn"},
	{id: 119, name: "Sandshrew"},
	{id: 120, name: "Sandslash"},
	{id: 121, name: "Scyther"},
	{id: 122, name: "Seadra"},
	{id: 123, name: "Seaking"},
	{id: 124, name: "Seel"},
	{id: 125, name: "Shellder"},
	{id: 126, name: "Slowbro"},
	{id: 127, name: "Slowpoke"},
	{id: 128, name: "Snorlax"},
	{id: 129, name: "Spearow"},
	{id: 130, name: "Squirtle"},
	{id: 131, name: "Starmie"},
	{id: 132, name: "Staryu"},
	{id: 133, name: "Tangela"},
	{id: 134, name: "Tauros"},
	{id: 135, name: "Tentacool"},
	{id: 136, name: "Tentacruel"},
	{id: 137, name: "Vaporeon"},
	{id: 138, name: "Venomoth"},
	{id: 139, name: "Venonat"},
	{id: 140, name: "Venusaur"},
	{id: 141, name: "Victreebel"},
	{id: 142, name: "Vileplume"},
	{id: 143, name: "Voltorb"},
	{id: 144, name: "Vulpix"},
	{id: 145, name: "Wartortle"},
	{id: 146, name: "Weedle"},
	{id: 147, name: "Weepinbell"},
	{id: 148, name: "Weezing"},
	{id: 149, name: "Wigglytuff"},
	{id: 150, name: "Zapdos"},
	{id: 151, name: "Zubat"},
];

const getRandomPokemon = (count) => {
	const shuffled = [...POKEMON_LIST].sort(() => 0.5 - Math.random());
	return shuffled.slice(0, count).map((pokemon) => ({
		pokemonId: pokemon.id,
		pokemonName: pokemon.name,
	}));
};

const generateGameCards = (pokemonList) => {
	const cards = [];

	pokemonList.forEach((pokemon) => {
		cards.push({
			pokemonId: pokemon.pokemonId,
			pokemonName: pokemon.pokemonName,
			isMatched: false,
			matchedBy: null,
		});
		cards.push({
			pokemonId: pokemon.pokemonId,
			pokemonName: pokemon.pokemonName,
			isMatched: false,
			matchedBy: null,
		});
	});

	for (let i = cards.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[cards[i], cards[j]] = [cards[j], cards[i]];
	}

	return cards;
};

module.exports = {
	getRandomPokemon,
	generateGameCards,
};
